# Generated by Django 5.2.9 on 2025-12-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('bureau_vote', models.CharField(max_length=150)),
                ('statut', models.CharField(default='Actif', max_length=50)),
            ],
        ),
    ]
