# Generated by Django 5.2.9 on 2025-12-17 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observateur',
            old_name='bureau_vote',
            new_name='commune',
        ),
        migrations.RemoveField(
            model_name='observateur',
            name='statut',
        ),
        migrations.AddField(
            model_name='observateur',
            name='picture',
            field=models.FileField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='observateur',
            name='prefecture',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
